<?php

namespace AppBundle\Repository;

/**
 * MachineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MachineRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOwnerItems($owner)
    {
        $query=$this->createQueryBuilder('m')
            ->join('m.sensors','s')
            ->join('s.sensorType','t')
            ->where('m.user = :user')
            ->setParameter('user',$owner)
            ->getQuery();
        return $query->getResult();
    }    
    

}
