<?php

namespace AppBundle\Repository;

/**
 * MachineStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MachineStatusRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLatestStatus($machine)
    {
        $query=$this->createQueryBuilder('ms')
            ->where('ms.machine = :machine')
            ->andWhere('ms.isRequest = false')
            ->setParameter('machine',$machine)
            ->orderBy('ms.id','DESC')
            ->setMaxResults(1)
            ->getQuery();
        return $query->getSingleResult();        
    }
    
    public function getLatestStatusOrRequest($machine)
    {
        $query=$this->createQueryBuilder('ms')
            ->where('ms.machine = :machine')
            ->setParameter('machine',$machine)
            ->orderBy('ms.id','DESC')
            ->setMaxResults(1)
            ->getQuery();
        return $query->getSingleResult();        
    }
}
