<?php

namespace AppBundle\Repository;

/**
 * SensorTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SensorTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
